import fs from "node:fs";
import { build } from "esbuild";
import { parse } from "acorn";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { catalog, protocolVersion, version } from "../src/catalog.mjs";
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
process.chdir(repo);
fs.mkdirSync("build/scripts", { recursive: true });
const output = fs.realpathSync("build/scripts");
if (!output.startsWith(repo + path.sep))
  throw new Error("Build output must stay inside this checkout.");
for (const file of fs.readdirSync(output)) {
  if (file.endsWith(".jsx") && file !== "mcp-bridge-auto.jsx")
    fs.unlinkSync(path.join(output, file));
}
await build({
  entryPoints: ["src/index.ts", "src/bridge-client.ts", "src/preview.ts"],
  bundle: true,
  platform: "node",
  format: "esm",
  outdir: "build",
  packages: "external"
});
const parts = [
  "src/bridge/json.jsx",
  "src/shared/validate.js",
  "src/bridge/editing.jsx",
  "src/bridge/operations.jsx",
  "src/bridge/panel.jsx"
].map((f) => fs.readFileSync(f, "utf8").replace(/^export /gm, ""));
const panel = `// Generated by scripts/build.mjs; edit src/bridge and src/shared instead.\n(function(thisObj){\nvar AE_VERSION=${JSON.stringify(version)}, AE_PROTOCOL=${protocolVersion}, AE_CATALOG=${JSON.stringify(catalog)};\n${parts.join("\n")}\n}(this));\n`;
parse(panel, { ecmaVersion: 3 });
fs.writeFileSync("build/scripts/mcp-bridge-auto.jsx", panel, "utf8");
console.error("Built server and ES3-checked panel " + version);
